#!/bin/bash
filename="mateIn8"
i=0
while read -r line
do
   echo $line
   log=log.mate.$i
   i=$((i+1))
   echo $line > $log
   ./Dist/minic_dev_linux_x64_see4.2 -mateFinder "$line" 12  >> $log
   if [ $(grep -c 9992 $log) == 0 ]; then
      echo "mate not found"
   else
      echo "OK"
      echo $line >> lines
      grep Best $log | awk -F: '{print $NF}' >> lines
   fi
done < "$filename"
